### ISSUE TITLE
Fitnesse - Test Page is Ignored

### ISSUE THREAD

**Issue by MJIndhuja** [unclebob/fitnesse#1165]
Hi,
I would like to get help on my fitnesse code. 

When I run my test page, the below result is shown.

Test Pages: 0 right, 0 wrong, 1 ignored, 0 exceptions     Assertions: 0 right, 0 wrong, 0 ignored, 0 exceptions (0.649 seconds)

Any reasons for my test page to be ignored? Pls help on this.

**Comment by tcnh** [comment]
Sharing the content of your page would help.

**Comment by MJIndhuja** [comment]
[Fitnesse Issue.docx](https://github.com/unclebob/fitnesse/files/2636021/Fitnesse.Issue.docx)


Hi, Pls loo into the attachment for the code and the Test Result Page.

**Comment by mgaertne** [comment]
I think you should go through a basic fitnesse tutorial. As I don't get what you try to achieve there from the code you wrote, maybe a good starting point would be the Airport Test Sampler: https://github.com/mgaertne/Airport-Test-Sampler/tree/master/FitNesse

**Comment by MJIndhuja** [comment]
Hi, Thanks for sharing the basic tutorials.

Now I'm getting a different issue.. 

Kindly look into the attachment and let me know what went wrong in the code. 
Looking forward for your help.

Thanks.

[Fitnesse Issue 1.docx](https://github.com/unclebob/fitnesse/files/2644585/Fitnesse.Issue.1.docx)

**Comment by fhoeben** [comment]
In future please post your screenshots directly in this issue, this works much easier than having to download and open word documents.

It looks like fitnesse is trying to use the java source directly, and fails. This is not surprising as it needs the compiled version (i.e. the `.class` file and not a `.java`). 
Have you compiled the class (using IntelliJ or from the command line)?
You probably need to setup the `!path` in your wiki pages to point to the compiler output instead of the source directory.

In notice in your code that you are also trying to start a chrome instance using selenium. This usually also requires a bit of setup before it works. There are standard plugins/fixtures that help you write such tests, see http://fitnesse.org/PlugIns#SLiMfixturesslimfixtures.

Besides the test sampler pointed out by @mgaertne you could also look at [my sample project](https://github.com/fhoeben/sample-fitnesse-project) which aims at allowing test development with minimal/no Java coding and maximum functional testing. A step by step guide how to set this up on your local Windows machine is also available: https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/Installation-Guide.

**Comment by woodybrood** [comment]
Wondering if we should just close this one out. It's been a year and we don't have anything actionable.

**Comment by woodybrood** [comment]
Closing due to lack of additional information.
