### ISSUE TITLE
Question: Accessing url parameters at run time

### ISSUE THREAD

**Issue by dbrown8674** [unclebob/fitnesse#1184]
Is there a way to access parameters set in the URL at run time?

For example if I run a test with this URL `http://localhost:8000/FrontPage.SamplePage.Testsuite.t1?test&var1=val1&var2=val2` and I wanted to access these values from a fixture without explicitly passing them to the fixture.

Also is there a way to access variables like PAGE_NAME and PAGE_PATH from inside of the code without passing them to the fixture?

**Comment by fhoeben** [comment]
As far as I'm aware you can access the URL parameters from the wiki (like other variables) or in a plugin (e.g. custom slim table), but not directly from fixture code.
You have to explicitly pass them to fixtures from the wiki.

**Comment by dbrown8674** [comment]
I'm pretty sure you're correct, but I'm hoping there is a way I can access them even if it's hacky. Maybe some one else has had the same problem and found a solution. I've spent a considerable amount of time looking into this and this is my last resort before I give up and just pass the variables via json or something.

**Comment by fhoeben** [comment]
Can I ask why you need/want to pass arguments this way? What are you trying to achieve?

**Comment by dbrown8674** [comment]
Parallel parameterized execution of fitnesse tests from inside of the fitnesse wiki. There are a bunch of roads I've already went down but this would be my preferred method as it gives me a lot of flexibility of how my fixtures behave.

**Comment by fhoeben** [comment]
I'm not sure I quite understand what you mean. 

I would guess you mean being able to run the same test page multiple times, in parallel, where the URL parameters define the variables that are different for each run? So the point is that you maintain one wiki page (or one suite of pages) but different parameters can be supplied at execution time? But in that case I would suggest the wiki page can pass the variables to the fixture: the wiki page contains the variable usage, but either the URL (variable values specified in the URL are given precedence over variables defined on the page), or a parent page if you would use [symbolic links](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.SymbolicLinks), defines the values for them.

**Comment by dbrown8674** [comment]
Thanks for the idea I'll look at it when I'm back at work on Monday, but my understanding is that it still wont let me pass parameters to a fixture without using them in a fixture and not what I'm trying to do since the parameters need to be able to be assigned dynamically.

Your understanding of what I'm doing is accurate though, running fitnesse tests in parallel with the parameters passed by the fixture that runs them.

The ideal solution is a function that's available to the fixture that would return the map of variables that the test currently can reference.

**Comment by fhoeben** [comment]
If the wiki passes `${var1}` to a fixture and the URL contains `?var1=foo` the fixture will receive `foo` as value (and this will be explicit in the test report). Is that not the level of dynamic behaviour you are looking for?

I personally like the approach of symbolic links because it allows sets of variable values to be defined explicitly in the wiki and a run with them can be started by just starting the right suite (without having to supply the values each time). But this is only appropriate if the values are not fully dynamic (i.e. different each time) but there is a fixed set (of combinations of variables) of test configurations to be run.

I also know of users that employ a 'hybrid' approach to tackle the issue of running multiple very similar test suites parameterised by al (large set) of variables. They have a single page that contains a (large) table defining the variables (as rows) and a column for each suite. This is the single configuration point of the sets of variables to test with. When this page is executed it generates a root-suite-page containing `!define` statements for all variables and a symbolic links to the test pages to be run. The actual test run then starts each of the suites.
A small example of such a configuration page can be found at

- https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite.wiki and 
 - https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite/SuiteGenerator.wiki, 
generic tests below 
 - https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite 
and test report pages at: 
 - https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.GeneratedSymbolicLinkSuite.SuiteSetUp.html, 
 - https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.GeneratedSymbolicLinkSuite.EnLocaleTests.Tests.JsonHttpTest.html, 
 - https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.GeneratedSymbolicLinkSuite.NlLocaleTests.Tests.JsonHttpTest.html

**Comment by dbrown8674** [comment]
Using symbolic links is interesting but what I was trying to avoid. I really didn't want to have big variable container pages that need to be maintained. I'm going to mark this as closed and maybe make a feature request in the future for this. Thanks for the help though.
