### ISSUE TITLE
Spring-Boot selfbootable jar problem

### ISSUE THREAD

**Issue by FloresStefano** [unclebob/fitnesse#1192]
Hi,
I would like to run fitnesse in a spring-boot (jar) autostatable project.
In this way I would like to have a self-starting jar that with a double-click starts fitnesse.

```
        <dependency>
            <groupId>org.fitnesse</groupId>
            <artifactId>fitnesse</artifactId>
            <version>20190216</version>
        </dependency>

```

```
@SpringBootApplication
public class Application {

    public static void main(String[] args) {

        SpringApplication.run(Application.class, args);

        Arguments arguments = new Arguments(new String[]{"-p", "8888"});

        try {
            Integer exitCode = new FitNesseMain().launchFitNesse(arguments);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
This simple code work correctly if I run it from my intellij.

Wiki server work fine.

BUT if I run springboot project by maven cmd: 

`mvn spring-boot:run`   

or double click on my spring-boot jar  

`acceptance-1.0.0.jar (with all dependecies embedded)`

Wiki server DONT work correctly, Some CSS and resources are broken.

![image](https://user-images.githubusercontent.com/28659839/53342056-6f873200-390d-11e9-9a94-97bd007cfb46.png)

My network:

![image](https://user-images.githubusercontent.com/28659839/53342149-a4938480-390d-11e9-925d-ff27d29fca45.png)

Any idea?

**Comment by fhoeben** [comment]
I would suspect this is because spring-boot has its own url mapping that prevents the request from reaching the responder in fitnesse that would serve content from the `files section`.

But may I ask: why do you need to use spring-boot to start a fitnesse wiki server, the `standalone-jar` published for fitnesse is already runnable by double clicking? Only it will listen on port 80 by default. You could create your own main class that just calls FitNesseMain (like your code does) and rebundle with a different manifest to indicate the main class to use on double click.
Or (much simpler) just create a batch file or shell script that does `java -jar fitnesse20190216-standalone.zip - p 8888` and click that.

The standalone.zip is also published to maven central: 
```
<groupId>org.fitnesse</groupId>
<artifactId>fitnesse</artifactId>
<version>20190216</version>
<classifier>standalone</classifier>
```
