### ISSUE TITLE
variables defined in SuiteSetUp page can't be used in test page

### ISSUE THREAD

**Issue by jinlxz** [unclebob/fitnesse#1205]
Hi, 

I found that variables defined in SuiteSetUp page can't be used in test page, the project has the following structure:
```
SuiteSetUp
SuiteA
|__ TestPage1
```

I defined a variable **varName1** in SuiteSetUp, I reference the variable in the page TestPage1, the value of the variable can be displayed in page TestPage1, but when I run the page TestPage1, it failed with an error saying that "undefined variable: varName1", I have read the documentation [Variable Scope](http://fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupVariables), I think the variable should be accessed in the test page as the SuiteSetUp page is included in the test page implicitly, but the fact is in reverse, does anyone know the reason for it?

Besides I hope the behavior I expected can be implemented in future if the behavior is not a bug

Fitnesse version: Release v20180127

thanks.

**Comment by fhoeben** [comment]
I believe this is not a bug. Variables defined in **ancestor** pages are accessible from a test page, and SuiteSetUp is not an ancestor, but a sibling.
That the variable is known in TestPage1 when it is viewed suprises me.

To make the variable accessible, define it in the page SuiteA.

Slim symbols which are given a value in a SuiteSetUp can be used in test pages in that suite (although I believe their value is not shown correctly in the test report, the correct value is used)

**Comment by jinlxz** [comment]
Sorry that I made a mistake on the project structure when writing this issue, the SuiteSetUp page is a sibling of the page SuiteA, not the page TestPage1, I have corrected it.

In this case SuiteSetUp page is included in the test page implicitly by Fitnesse, but the variable in SuiteSetUp can not be accessed in the test page, it is wired although I know it is by design.
is it possible to implement that referencing variables defined in both ancestor pages and SuiteSetUp page in a test page? as this behavior is common and natural in other testing framework, e.g. RobotFramework. 

Thanks

**Comment by fhoeben** [comment]
I understand what you are asking but, like you say, the current setup is by design and a SuiteSetUp is not a direct ancestor so the variable is not accessible by design.

Can I ask why you want to define the variable in SuiteSetUp, and cannot define it in the parent of both SuiteA and SuiteSetUp? Since variables as not dynamic during the test run, but statically resolved before the test starts I personally have not had that need. 
(I have needed to capture values I received during SuiteSetUp for use during the test run, but for those I have always used Slim symbols whose value can be set in SuiteSetUp and then retrieved in test pages.)

**Comment by jinlxz** [comment]
@fhoeben Thank you, you are right variables can be defined in the parent of both SuiteA and SuiteSetUp, it can solve my problem.
