### ISSUE TITLE
Order of suites executed should not depend on presence of SuiteSetup

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#1229]
The order that tests is executed shouldn't matter, but for reporting purposes it can be convenient if ordering remains the same between runs.
At the moment the ordering of tests by FitNesse is stable, also when working with nested suites (e.g. Suite1 contains SubSuite1 and SubSuite2). BUT the ordering of execution of nested suites changes based on whether they have their own SuiteSetUp or SuiteTearDown pages.

So initially (without SuiteSetUp inside SubSuite1) SubSuite1 is executed before SubSuite2, but when a SuiteSetUp is added inside SubSuite1 it could happen that SubSuite2 is suddenly executed before SubSuite1. This is not always the case, but can happen. 
For test outcome it shouldn't matter, but it can be surprising and make test report more complex to read/explain. (See for instance https://stackoverflow.com/questions/56597945/alternative-for-nested-suitesetups-that-maintains-ordering)

In the past there has been an issue about test ordering (#131), which was marked as "won't fix". The discussion in that issue seemed to go in the direction that test ordering should not matter. While that is true in general. Test ordering by FitNesse is normally quite predictable and it seems odd that adding a SuiteSetUp page changes ordering, sometimes.

**Comment by ALuckyGuy** [comment]
I agree with you that the order should be consistent, and it *can* happen that the order matters. 

For me it's common to have sub-suites where when executed as part of a larger suite, the order *is* important. I name my suites and test explicitly so I know the order they execute. For instance I might have one suite of tests that hires employees, and another suites of tests that verify I can perform certain job actions on newly hired employees. Of course I need the first sub-suite to execute before I can run the next suite... the order is very important in this case and I don't think it's an uncommon or unreasonable expectation.

**Comment by fhoeben** [comment]
Another thing I noticed when looking at the code determining suite ordering and -setup and -teardown is that the same SuiteSetUp or SuiteTearDown may be executed more than once. 

FitNesse creates groups of tests that have the same SuiteSetUp and SuiteTearDown and runs these groups one after the other. For each group it runs the appropriate setup and teardown. But it does not consider whether another group uses the same setup or teardown. So if two groups share the same setup (but a different teardown) the setup is executed twice.

This is also not what I would expect. I would expect the SuiteSetUp to be executed once, before the first test in the suite it belongs to, and the SuiteTearDown to be executed once, after the last test in its suite.

**Comment by JessefSpecialisterren** [comment]
@fhoeben I'll respond to the questions you asked on StackOverflow here, as this seems a more appropriate place.

> Is the only problem you have the order on the overall test report (i.e. the page listing all tests in a single page), or is there something more fundamental?

It's not just the order in the report that changes, the whole test execution order changes. When running a suite containing sub suites, the sub suites are normally executed in lexicographical order. Adding nested SuiteSetUps can make that no longer true.

> I'm a bit unclear at what exactly you want to achieve. You indicate the order of tests changes. Can you make explicit what is the order with and without SubSuite2.SuiteSetup? And what is the order you aim to get?

If the test hierarchy is as follows:

* TopSuite
  * SubSuite1
    * [tests]
  * SubSuite2
    * [tests]
    * SuiteSetUp
  * SubSuite3
    * [tests]
  * SuiteSetUp

Then the sub suites are consistently executed in the order 1 - 3 - 2 instead of the expected 1 - 2 - 3:
![image](https://user-images.githubusercontent.com/36038882/59588088-183ce580-90e7-11e9-86c9-da3d323bbb74.png)
Removing the SuiteSetUp from SubSuite2 brings the order back to a consistent 1 - 2 - 3.
I want to achieve that the sub suites consistently run in the order 1 - 2 - 3 while SubSuite2's SuiteSetUp still gets executed right before the first test of SubSuite2.

> Have you tried giving all sub suites their own SuiteSetup? What was the effect of that?

I did, the test order still remained 1 - 3 - 2. Debugging FitNesse showed that the suites were added to https://github.com/unclebob/fitnesse/blob/b822c01ee11a93d99b0d40536a4f5ea20598fe33/src/fitnesse/testrunner/PageListSetUpTearDownSurrounder.java#L28 in 1 - 2 - 3 order, so the 1 - 3 - 2 is probably the HashMap's undefined order coming into play.

> I created github.com/unclebob/fitnesse/issues/1229 to see whether this can be addressed.

Great! Would you like me to test the PR to see if it results in the desired test execution order?

**Comment by fhoeben** [comment]
I think this PR should give you exactly what you expect. Let me know!

**Comment by fhoeben** [comment]
Try 20190628 and add `!define ALL_UNCLE_SUITE_SETUPS {true}` to your top-level suite

**Comment by JessefSpecialisterren** [comment]
Awesome, that seems to work! Due to vacations, it'll be a while before we integrate it into the project that lead to this bug report in the first place, but all the tests I've run indicate that this solves the problem. Feel free to close this issue, and I accepted your answer on Stack Overflow. Thanks for your work!
