### ISSUE TITLE
User is unable able to log in FitNess using LDAP

### ISSUE THREAD

**Issue by superherosalive** [unclebob/fitnesse#1278]
We notice user is not able to log into FiNesse when their accounts have migrated to office365.  We're using a LDAP plugin and it doesn't seem to support UPN change.  It always assumes the format of SAMAccountName@Rootdomain.  

Does FitNess natively support LDAP or does it still require a separate plugin?  I'm looking for an alternative plugin and most of them are outdated or no longer maintain by the developer.  Which method do you all use to authenticate your users through LDAP?  Any help or guidance is greatly appreciated?

**Comment by fhoeben** [comment]
I have to admit I never used any LDAP integration, but I believe there is no native support.
I tend to use FitNesse locally to develop tests, store the wiki pages in version control and then run them from a CI server.

**Comment by superherosalive** [comment]
Thanks @fhoeben for your comment.

Would this be something the community consider to add to FitNesse as feature in future releases?  I would love to have LDAP supported natively instead.  In the meantime, do you have any recommendations for getting FitNesse to work with LDAP?  I'm hoping if there's any other alternatives or workaround.

**Comment by fhoeben** [comment]
I'm not opposed to having LDAP support, so I would welcome a PR.

But personally, I have no access to an LDAP server or need to use it...

**Comment by superherosalive** [comment]
I understand not everyone would need authentication.  How would I propose a PR for native support of LDAP?

**Comment by fhoeben** [comment]
Just fork the repo, figure out what is needed to support it, make it work, write one or a couple of wiki pages documenting its use/configuration and create a PR. :-)

But make sure to check whether you can do it without making the distribution much larger (because of needed .jars and the like). Since it is not needed for many (most?) maybe it would be better as a plugin that one can optionally add to one's installation.
If changes in the core project are needed to support such a plugin than just make a PR on the main project for those.

Plugin can be added by placing their jars in the plugins directory and will be automatically picked up if they contain the right meta-data, in the manifest file. On the fitnesse.org site there is a page where you can mention/announce availability of your plugin.

**Comment by woodybrood** [comment]
Can't you fork https://github.com/timander/fitnesse-ldap-authenticator and update it instead? Is there a reason for you that it HAS to be a part of FitNesse and not a plugin.

**Comment by superherosalive** [comment]
Thanks @woodybrood.  Does not have to be part of FitNesse but it just needs to be integrated with FitNesse.  I'll fork it and try to update it.  If I ran into any issue, is it ok to post it here for support?
