### ISSUE TITLE
Update bootstrap and jquery because of vulnerabilities

### ISSUE THREAD

**Issue by Eddie1802** [unclebob/fitnesse#1289]
Running an [OWASP dependency check](https://owasp.org/www-project-dependency-check/) on our test framework showed several vulnerabilities in both the bootstrap and jquery versions currently used by FitNesse (20200501).

**bootstrap.js 3.3.6:**
https://nvd.nist.gov/vuln/detail/CVE-2018-14040
https://nvd.nist.gov/vuln/detail/CVE-2018-14041
https://nvd.nist.gov/vuln/detail/CVE-2018-14042
https://nvd.nist.gov/vuln/detail/CVE-2019-8331

**jquery-1.11.3.min.js:**
https://nvd.nist.gov/vuln/detail/CVE-2015-9251
https://nvd.nist.gov/vuln/detail/CVE-2019-11358

Would it be possible to update both to a newer version without these vulnerabilities?
For bootstrap this would mean updating to version 3.5.0 or higher.
For jquery version 3.4.0 or higher is needed.

**Comment by fhoeben** [comment]
Of course it is possible ;-)

I believe I tried upgrading the JavaScript dependencies some time ago and found that it was not trivial. But I don't believe I tried _very_ hard, so it might not be too hard.

For me this has not been a priority as I never run the wiki on a server. I use a local installation which is not accessible remotely and on the CI server no webserver is needed for FitNesse as I run the tests via jUnit.

But for the project it would of course be very good to upgrade these.

I believe some work was done to upgrade bootstap already: https://gun88.github.io/fitnesse-bootstrap-4/FrontPage
@gun88 did you ever get any further upgrading bootstrap for the whole project, and did you look at jQuery?

**Comment by tcnh** [comment]
We've recently upgraded bootstrap-plus to use JQ 3.4.1 and Bootstrap 4.4.1. Have a look at: https://praegus.github.io/fitnesse-bootstrap-plus-theme/ (Also has an upgraded codemirror editor and a couple of tweaks that makes FitNesse much more usable when using Slim Fixtures)

Upgrading JQ and Bottstrap was not that hard, just needed a few removed methods replaced with there respective replacements. I can see if I can just port the related commits to bootstrap

**Comment by gun88** [comment]
> I believe some work was done to upgrade bootstap already: https://gun88.github.io/fitnesse-bootstrap-4/FrontPage
> @gun88 did you ever get any further upgrading bootstrap for the whole project, and did you look at jQuery?

Hi, I always developed the `fitnesse-bootstrap-4` as a plugin since FitNesse is very customizable via the PluginFeatureFactory and it works great. However, to use it for the whole project, the only thing needed is to overwrite files.

The challenge was also to use bootstrap-4 without break original acceptance tests, so a minimal set of templates was modified, but if used as default theme we might consider to improve some Velocity template and redefine tests.

I never upgraded jQuery because I wasn't concerned about vulnerabilities, since I usually run FitNesse into an intranet. Trying to replace jQuery 1 with jQuery 3 I got an error switching to `rich text editor`, so I think that probably some js library or vm template needs to be upgraded too.

**Comment by fhoeben** [comment]
@tcnh any progress regarding porting your changes?

**Comment by tcnh** [comment]
Thanks for the reminder. See the referenced PR!
