### ISSUE TITLE
Provide flag to stop slimserver starting locally to avoid conflicts with docker hosted slimservers

### ISSUE THREAD

**Issue by millerjp** [unclebob/fitnesse#1315]
**Is your feature request related to a problem? Please describe.**
I have some test scenarios which require my tests to be executed in a complex network setup. To do this the fitnesse tests need to be executed in a remote network (such as a local docker-compose) via a slim server deployed in docker-compose running on localhost. However, fitnesse still attempts to start slimserver locally on the configured port. This causes errors as the address is alreay in use.

**Describe the solution you'd like**
Provide a command line flag or property to stop slimserver beeing started locally.

**Describe alternatives you've considered**
There isnt really one other than run everything in the docker network which is not ideal.

**Additional context**

**Comment by fhoeben** [comment]
Have you tried setting `manually.start.test.runner` or `MANUALLY_START_TEST_RUNNER` to `true`?
I didn't see this in the documentation, but I believe this might achieve exactly what you need...

**Comment by millerjp** [comment]
@fhoeben yes - I just found this and it does the job. I was just about to close this.

However, I have hit another problem in that the slim port gets incremented by 1 on each test run (up to +10) http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.SlimProtocol.PortManagement .

This auto incrementing of the ports makes this approach unusable as my slimserver in docker is only listening on the initial port, so after the first run it cant connect.

**Comment by fhoeben** [comment]
I tend to agree with you the port number (if provided) should not be auto-incremented when multiple runs are started sequentially (only when they are started in parallel). So instead of a conditional around the auto-increment I believe the counter should be decremented once a test run is complete. 
But that does not seem to be implemented :-(

A workaround that might work is to set `slim.pool.size` to `1`...

Looking at the code it appears to me the intended usage in a scenario such as yours is for there to be a local program that will be started by FitNesse which will receive the port number (base port number + auto increment) the server is expected to listen on; this program should ensure the slim server is started and listens on that port and can provide output for the execution log. Using this approach the manual start variables should no be needed and the auto increment is no problem.

In your situation I believe this could be done:
- before you start a test run use docker(-compose) to start a container with the correct network setup, the slim server and fixture code. Expose the ports that slim might use (`slim.port`..`slim.port + slim.pool.size`). Create a container, but do not make it start the slim server yet.
- create a (local) shell script that uses 'docker run' to start a slim server in that container using the port supplied. It should not run in daemon mode, but kill the process when it is stopped.
- use that script as slim command (i.e. each time a run is started it will launch a new server inside the docker container)

Using this approach the manual start variables should not be needed.

**Comment by millerjp** [comment]
@fhoeben thanks - I can try that. The only thing I am not sure of is how to have the hookin to execute the script to start slimserver in the container. Would that be done by overriding COMMAND_PATTERN?

**Comment by fhoeben** [comment]
Indeed I believe setting `COMMAND_PATTERN` should work

**Comment by millerjp** [comment]
Thanks - I will give that a go. Really appreciate the pointers!
