### ISSUE TITLE
Compatibility Java 17 LTS

### ISSUE THREAD

**Issue by HoneyBadgerSeeker** [unclebob/fitnesse#1337]
**Describe the bug**
FitNesse execution crash at the first custom fixture.
The import package is fine.
I know FitNesse doesn't support java 15 as stated here (http://fitnesse.org/FitNesseDownload). But it should be handled by the lastest LTS JAVA version.

**To Reproduce**
Launching a FitNesse test with JDK 17 LTS with the following fixture

**Fixture code**
```
public class BuildProp {
    private static final Properties properties = new Properties();
    public String key;
    public String value;
    public BuildProp() {
        properties.put("stuff", "stuff");
    }
    public void setKey(String key) {
        this.key = key;
    }
    public void setValue(String value) {
        properties.put(this.key, value);
    }
}
```

Fixture called this way:
```
!|BuildProp|
|key |value|
|a   |b    |
```

**Expected behavior**
Test is executing normally.

**Stack Trace**
java.lang.IllegalAccessError: superclass access check failed: class com.github.tomakehurst.wiremock.common.Xml$SkipResolvingEntitiesDocumentBuilderFactory (in unnamed module @0x104448e4) cannot access class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp to unnamed module @0x104448e4

**Configuration:**
 - Version [e.g. 20210606] of FitNesse
 - Test System: [e.g. Slim]

**Comment by HoneyBadgerSeeker** [comment]
To solve this issue, I added the last version of Junit as dependency in my pom.xml

**Comment by LeiYangGH** [comment]
i got following exception when starting fitnesse 20240219 as a maven dependency, under open jdk 17:

Mar 15, 2024 8:51:23 AM fitnesseMain.FitNesseMain main
SEVERE: Error while starting the FitNesse
org.apache.velocity.exception.VelocityException: The specified class for ResourceManager (org.apache.velocity.runtime.resource.ResourceManagerImpl) does not exist or is not accessible to the current classloader.
        at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:806)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:282)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:749)
        at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:122)
        at fitnesse.html.template.PageFactory.newVelocityEngine(PageFactory.java:71)
        at fitnesse.html.template.PageFactory.<init>(PageFactory.java:22)

i'm not sure this is caused by jdk version mismatch or not. i'm sure my same code works well under jdk11. and i can run fitnesse-standalone.jar using jdk 17.
