### ISSUE TITLE
Site is using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by mbiesiad** [unclebob/fitnesse#1372]
**Describe the bug**
Site is using HTTP instead of HTTPS. Site is marked as "not secure" by browsers.

**To Reproduce**
1. Go to 'http://fitnesse.org/'
2. See info about "not secure"

**Expected behavior**
Mentioned page is using HTTPS.

Best wishes,

**Comment by millerthegorilla** [comment]
This affects me as I cannot even visit the site due to my browser settings.
And I am currently reading the clean code book, so I kind of wanted a quick peek.
Perhaps use certbot?
I use a container that has certbot that sets itself up automatically with some environment variables that I pass in when I create the container.  Dead easy, and entirely clean and cleanable!

**Comment by fhoeben** [comment]
Fixed
