### ISSUE TITLE
Fitnesse.org hacked

### ISSUE THREAD

**Issue by weaverj** [unclebob/fitnesse#1438]
**Describe the bug**
The download page of fitnesse.org (http://fitnesse.org/FitNesseDownload) appears to have been hacked.  Doesn't appear that fitnesse.org is running with any kind of security certificate either - in general probably needs some TLC.

**To Reproduce**
http://fitnesse.org/FitNesseDownload)

**Expected behavior**
Something not involving pornomedia

**Comment by fhoeben** [comment]
Thanks for reporting this.
Fortunately the site was only 'hacked' in so far that the regular wiki editing features were used to change the downloads page.

This was possible due to the fact that we accidentally left the editing features enabled with the latest deployment. This has now been corrected and the official content restored to all pages.

**Comment by weaverj** [comment]
Ah, yep, I kind of wondered if it had just been a wiki edit on what was supposed to be a non-editable page.  Much better than a Wordpress hacked instance - had to give up on one of those once!  Thanks for quick fix!
