### ISSUE TITLE
Fitnesse problem with xpath

### ISSUE THREAD

**Issue by Mrle1992** [unclebob/fitnesse#1445]
This is a scenario |scenario|Open tab on dashboard |tab |
|click |xpath=//*[contains(@class,'nav-link') and text()='@tab']|

And this is the script
Open the 'Value Chain' tab and check if the tab is selected.
script
Open the Value Chain app tab
Wait until the Value Chain tab is selected

xpath is not good because it doesn't open the Value Chain tab for me

I tried for each tab to create a separate xpath like this

|scenario|Open tab on app |tab |
|click |xpath=//*[contains(@class, 'nav-tabs')]//*[text()='Assessment']|

|scenario|Open tab on app |tab |
|click |xpath=//*[contains(@class, 'nav-tabs')]//*[text()='Organizational']|

|scenario|Open tab on app |tab |
|click |xpath=//*[contains(@class, 'nav-tabs')]//*[text()='Value Chain']|

Now I come to the next problem. The problem is that instead of the Organizational tab, it opens the Value Chain tab. I could not solve this problem

**Comment by fhoeben** [comment]
I don't believe this is a problem for this project, but for the fixtures you are using.

I believe your examples would benefit from the usage of a '[code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)' in your description.

---
Some remarks on the actual content of your comment. I would recommend that you use `@{tab}` to indicate where you use your scenario's parameter. And you don't indicate where the placeholder should come from

In your script you don't seem to call the scenario you define. 

In the xpaths you use I notice that you have `@Class`, which is hardly ever used in HTML. Shouldn't that be `@class`?
In the specific xpaths you use the `//` twice which means the first part (everything before the second `//`) is effectively ignored since you go back to the root of the document.

Combining all this I would think you are actually looking to do something like:
```
|scenario|Open the _ tab on dashboard |tab |
|click |xpath=//*[contains(@class,'nav-link') and text()='@{tab}']|

|script|<name of fixture|
|Open the |Value Chain | tab on dashboard|
|Wait until the |Value Chain| tab is selected|
```

I recommend that you test your xpaths using the developer console of your browser. This probably allows quicker feedback than trying them only via fixtures.

**Comment by Mrle1992** [comment]
I made it too complicated. I'm trying to explain my problem as easily as possible so that you can understand what I need.

This is the scenario I have in my tests

```
|scenario|Open tab on app|tab|
|click|xpath=//*[contains(@class,'nav-tabs')]//*[text()='@tab']|

|scenario        |Wait until tab                   |tab                   |is selected                  |
|wait for visible|xpath=//*[contains(@class,'nav-tabs')]//*[contains(@class,'active')]//*[text()='@tab']|
|check pending requests       
```

And this is the script from my test

Open tab 'Value Chain' and check if the tab is selected.

|script|
|Open tab on app| Value Chain|
|Wait until tab |Value  Chain|is selected| 

These are two scenarios for
Open tab on app and Wait until tab

And of course a picture of what I get at the end of the test in Fitnesse
![Untitled 333](https://github.com/unclebob/fitnesse/assets/142903765/3061e541-fb75-472c-9c1e-f48745cd6f79)

**Comment by fhoeben** [comment]
This is an issue with a fixture. Please open (an issue for that project](https://github.com/fhoeben/hsac-fitnesse-fixtures/issues)

P.S. In your latest comment I still see `//` twice in one xpath, so I expect the `click` will just click the first element with the supplied text, the `@class` clause will just be ignored.
