### ISSUE TITLE
Could approximately equal comparison be the default for numbers?

### ISSUE THREAD

**Issue by mbarchfe** [unclebob/fitnesse#403]
Hi,

I often forget to use ~= for comparing doubles. It is quite cumbersome in particular when copying data from spread sheets. In that case one has the expected values ready in one column but then has to create another column with the ~= prefix.

Would it make sense to use approximately equal as default for comparing numbers? One could check if the expected value is a number with fraction and then switch to ~= as comparison method.

An experimental implementation can be found here:
https://github.com/mbarchfe/fitnesse/commit/eb162f5233a0d36749da9621cff9dafb01cb08ae

Thanks 
Markus

**Comment by amolenaar** [comment]
I have to agree with Dan here. This is a rather small change with a possible big impact for existing users. You can also fix the formatting in the fixture (return a String) and just rely on string comparison. (I would prefer this over the slim table comparitors anyway, since it keeps the tables/examples cleaner).

I'll take the liberty of closing this issue. Please reopen if you want more discussion.
