### ISSUE TITLE
Enhancement: Display values that come from variables in a different color/style

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#556]
When a page isn't being edited, it can be easy to overlook the fact that certain values on the test page as coming from !define variables, especially when those !defines are higher up in the hierarchy of the current page. There's no visual cue that the page has dependencies on these variables, and you have to go into Edit mode to check.

Just as missing defines are displayed in gold to help bring attention to the fact that they're missing, it would be useful is existing substitutions were displayed in a different color as well. How about a nice magenta so they stand out?

**Comment by amolenaar** [comment]
I like the idea but... Pages are currently (for Fit and Slim) rendered as HTML before they're passed to the test system, so that means all markup will also be passed to the test system, which is probably not what you want.

**Comment by six42** [comment]
hi Amolenaar,
How has the problem you describe been fixed in #588.
If tables can be coloured should than this not also work for variables?

**Comment by amolenaar** [comment]
Hi,

You refer to #558 I suppose ;). The colouring is done on `tr` and `td` elements. Those are not passed to the test system. Suppose I have a table row like this (`out` maps to `outVal`):

    | in | ${out} |

Then this would translate to HTML formatted like this:

    <tr><td>in</td><td>outVal</td><tr>

The test system(s) read two values: `in` and `outVal`.
Now, say I want to highlight the replaced value, I end up with HTML formatted like this:

    <tr><td>in</td><td><span class="variable">outVal</span></td><tr>

Hence the test system will receive values  `in` and `<span class="variable">outVal</span>`. This is not what I would expect. I think changing it to only return the text in the `td`, instead of the html, is to intrusive a change for many users (considering the challenges I faces while cleaning up the Slim test system code).

BTW. I expect Slim hash tables not to be coloured.

It would be nice to have an opt-in solution for test systems that can deal with variable colouring, though. Maybe make it optional?

**Comment by six42** [comment]
Got it. Thanks for the detailed explication.

Am 25. Januar 2015 20:39:20 MEZ, schrieb Arjan Molenaar <notifications@github.com>:

**Comment by six42** [comment]
By the way LuckyGuy,

An alternative to variables might be symbols. 
If you use symbols the user sees this in view mode.

**Comment by amolenaar** [comment]
This issue can be closed, right? (if not, pls reopen :) )
