### ISSUE TITLE
Dropdown and radiobutton and no ID's

### ISSUE THREAD

**Issue by NPO1** [unclebob/fitnesse#647]
Hi

I am an new user of FitNesse and I have a problem with running a test in Fitnesse. For many elements there is an ID for recognizing. But it's not a database. So I use preferably names and values. So I can keep it simple. Is this not a better way to keep the test readable?

When I run my tests I get different results each time. They are good and green and than not. There's no logic in it as I see it. The error says the element doesn't exist. In Selenium they are recognized on the page. Although it's not implemented as a standard option to choose out. I written the xpath myself because Selenium doesn't suggest it nor by right click with the mouse on the webpage. The elements are radio and dropdown menu's. I have used several of these commands with targets and value, and they work fine. But as I get further in my testcase the latest elements do not work as aspected. How can this be resolved without using ID="blabla".

I use this:
Radiobutton, line:
|click;|//input[contains(@name, 'member.new') and contains(@value, 'false')]| or
|click;|//input[contains(@name, 'member.new') and contains(@value, 'true')]|
Dropdown, line:
|select;|//select[contains(@name, 'users.add')|NewUser|

I wonder also how I can make controles on above mentioned lines. And of course get these mentioned lines work.

**Comment by amolenaar** [comment]
Hi,

I think you're confused about what is FitNesse and what is not.

It looks to me your problem has to do with the fixtures you use from FitNesse. You'd better ask the author of your fixtures and the author of the application you're testing (your involved with the development of the application your testing, right?).

**Comment by NPO1** [comment]
Fitnesse is a testtool. I am indeed testing a webapplication. Can you explain to me what you mean by what FitNesse is and isn't. My confusion is the use of ID=''. Because this term is usually used in databases or to an unique substance.

**Comment by woodybrood** [comment]
FitNesse is a domain independent framework. It has no built in
functionality for web or database testing. These capabilities are
implemented as separate code and are used by FitNesse to perform the
actions listed in the tables in your FitNesse pages. For example, there is
no web testing functionality in FitNesse, but you can add it using Xebium.
Additionally there is no REST testing functionality, but you can add it
using RestFixture. Or you can write your own, which is what I've always
done.

So, if you are having issues with how objects are being identified or
interacted with in web pages, the issue almost undoubtedly rests in the
code that connects to Selenium or whatever too you are using. If you are.
Having issues with the pages rendering wrong or interpreting tables wrong,
or having issues with the order results are appearing, then that could be
in FitNesse, but could still have something to do with the code that is
specific to what you are testing.

So that said, what library to test web pages are you using? Have you tried
to contact the developers of the web driver code?

Or, if you are having issues with how to use FitNesse itself, you can reach
out to the FitNesse group on Yahoo and see if folks there can help with
ideas for designing test pages that do what you want.

Does that explain better?

Daniel A. Woodward
-------------------------
FitNesse using Slim and Java
@woodybrood
http://whotestedthis.com
