### ISSUE TITLE
RFC: Change of TestTextFormatter 

### ISSUE THREAD

**Issue by six42** [unclebob/fitnesse#680]
Hi,

I would like to slighly change the output of the text formatter.
I want to put the execution time at the front of each line. Currently it is at the end.
This would allow to easier see which tests are slow.
An example of the future output is below.

What do you think about this?
Are any other programs depending on the current output? (jenkins, junit, ...) 

java -jar  dist\fitnesse-standalone.jar -o -c "FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders?suite&format=text"

Starting Test System at 2015-34-14 14:34:32: slim:fitnesse.slim.SlimService.
. 0,031 sec R:0    W:0    I:0    E:0    - SuiteSetUp	(FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders.SuiteSetUp)
. 0,657 sec R:2    W:0    I:1    E:0    - TestErrorOccurred	(FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders.SuiteExecutionStatusMessages.TestErrorOccurred)
. 0,375 sec R:2    W:0    I:1    E:0    - TestExecutedOk	(FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders.SuiteExecutionStatusMessages.TestExecutedOk)
. 0,031 sec R:1    W:0    I:0    E:0    - DefinesFromSetupPagesShouldBeAvailableInTest	(FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders.SuiteResponder.DefinesFromSetupPagesShouldBeAvailableInTest)

**Comment by amolenaar** [comment]
AFAIK no tools depend on the text output format.

**Comment by mgaertne** [comment]
I don't think that depending for stuff like this on the output of a program is a proper way to handle it. Ideally, I would like to have a plugin structure where the TestTextFormatter would be one listener for, and others may plugin into the behavior there in order to analyze how long a test took. That said, I would suggest a Client-Observer-like structure here rather than depending on outputs that are most likely subject to change.
