### ISSUE TITLE
Execute TearDown on StopException

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#684]
Currently the TearDown for a Slim tests that throws a StopTest exception is not executed. This is not very intuitive (since different from TearDown handling in other (e.g. unit) test environments), which also show from the following quote from  FitNesse.UserGuide.WritingAcceptanceTests.SliM.ExceptionHandling: 
> Be warned, that if you throw a "StopTest" exception then the tear down for your test will not run. A fix for this is to run the tear down procedure before you throw the exception.

The fix suggested in the quote does not work for me as the test fixture throwing the exception is not aware of the content of the TearDown page.

- I believe the content of the TearDown page should be executed irrespective of whether the test was stopped or not. 
- On a SuiteStop exception not executing the TearDown is ok, but I would expect the SuitTearDown to be executed.

**Comment by amolenaar** [comment]
This would require quite some changes in the way tests are executed now. A `TestPage` needs to know about setup and teardown pages and the test systems need to handle them accordingly.

**Comment by mgurov** [comment]
The decision about whether to execute a next table is made at `fitnesse.testsystems.slim.SlimTestSystem#processTable` based on the state of the `stopTestCalled` and `stopSuiteCalled` attributes derived from the slim response. 

If we could mark a `fitnesse.testsystems.slim.tables.SlimTable` as teardown, that could be a hint for the `SlimTestSystem` to execute such table even after the stop has been called. 

On the other side, we know which tables came from the teardown pages at the moment we translate wiki to html (via `fitnesse.testrunner.WikiTestPage#getHtml` and ultimately at `fitnesse.wikitext.parser.Include#toTarget`). I suggest to mark the inserted tear-down links with html class (`teardown`) and use this knowledge when converting the produced html to the `SlimTable`s.

Linked is a [very dirty demo draft](/mgurov/fitnesse/commit/def86c105146711194be662a17d74b81f61343b3). If the maintainers of the project find this approach reasonable I could make a proper pull request out of it.

**Comment by mgurov** [comment]
In fact, at the moment the `SuiteTearDown` is executed on `StopTest` exceptions, which brings a limited workaround for the issue: do not throw `StopSuite` exceptions and release important resources at the `SuiteTearDown`. 

In more detail, the current handling of the tear down after special slim exceptions can be shown in this way: 

Page | StopTestException | StopSuiteException
------------ | ------------ | -------------
TearDown | 🔴  | 🔴
SuiteTearDown | ✅  | 🔴 

Desired state is probably something like this:

Page | StopTestException | StopSuiteException
------------ | ------------ | -------------
TearDown | ✅  | ✅ / ❓ 
SuiteTearDown | ✅  | ✅ 

The execution of the `TearDown` for a test skipped entirely due to a `StopSuite` exception can be seen as undesired. On the other hand it would be very much preferable to execute the TearDown of the test that has issued the StopSuite exception.
