### ISSUE TITLE
__EXCEPTION__:java.lang.NullPointerException Issue

### ISSUE THREAD

**Issue by taizione** [unclebob/fitnesse#752]
Hi, I use ScriptTable to do my testing, and I define a table below:

!include -c ConfigPage
| script | ParserAPI |
| setParameters | !{username:admin,password:123456} |
| doPost | !-https://xxxx:8445/passport/v1/login-! |
| show | showResponseMessage |

And in my ParserAPI java code, in method showResponseMessage, I call another method getValue(String outParametersList2, String responseMessage):

	public String showResponseMessage() {
		....
              return  getValue(String outParametersList2, String responseMessage);
}

      public getValue(String outParametersList2, String responseMessage){
     **do some action....
}

But It seems the parameters always be null when passing from showResponseMessage to getValue. Could you do me a favor for this issue? Thanks.

**Comment by amolenaar** [comment]
There seems to be a null-pointer in your code. The best way to solve it is to create a unit test that surfaces the issue.

Since this more a user question, rather than a technical issue with fitnesse I want to ask you to continue the rest of the conversation on the FitNesse mailinglist at http://groups.yahoo.com/group/fitnesse.
