### ISSUE TITLE
how can i import fitnesse source code into eclipse 

### ISSUE THREAD

**Issue by Samarelagouz** [unclebob/fitnesse#827]
how can i import fitnesse source code into eclipse

**Comment by amolenaar** [comment]
You may want to install the Ivy plugin for Eclipse (Apache IvyDE).

Import FitNesse via Project… -> Java -> Java Project from existing Ant Buildfile

It asks from a javac target to use. Just pick any. Make sure both src and test directories are marked as source paths.

Now for setting up Ivy:

Open Properties (right-mouse click). In Java Build Path select Libraries and Add Library… Select IvyDE. The Main settings are okay by default. On the Settings tab, select ivysettings.xml from the project.

That should do the trick.

Regards,

Arjan

**Comment by amolenaar** [comment]
Hi,
Question: what information is lacking from the README file? There is a section on IDE's there, but from your question I conclude there's information lacking.

**Comment by hansjoachim** [comment]
>Question: what information is lacking from the README file?

Some more details on how to set up development environment from scratch would be nice. :) For instance, mentioning that Eclipse can import from the Ant Buildfile is useful. I don't remember how I imported FitNesse, but I'm quite certain I didn't know about/did that. I _think_ I used IvyDE, but I guess it should also be ok to simply add the lib/ directory to the list of dependencies.

Another thing is for IntelliJ IDEA, in which I haven't found a way to import from Ant, so I ended up "creating a new project" and pointing it to the directory where I had already cloned FitNesse. It picks up src as the source directory, but I had to mark test as test sources manually (at least in newer versions of IntelliJ). Otherwise it refused to compile/run the tests. (Oh, and I also had to add the dependencies from lib/, but that is documented in the README at the moment.)

I don't remember whether I got FitNesse up and running in Netbeans, it's been a while since I tried with that IDE...

**Comment by reneintersys** [comment]
I had similar questions howto setup the eclipse project.

In the Readme.md it's just written:
> Apache Ivy is used for dependency management. Your IDE can be set up to support Ivy.
>    * In IntelliJ set IvyIDEA in "Project Structure" -> "Modules" -> "Dependencies".
>    * In Eclipse, install IvyDE and set it up.

"install IvyDE and set it up" should be more detailed to non-Ivy users.

Your post @amolenaar above was really helpful, therefore I recommend to add following text to the Readme.md

> * Import FitNesse via Project… -> Java -> Java Project from existing Ant Buildfile
>  * It asks from a javac target to use. Just pick any. Make sure both src and test directories are marked as source paths.
> * Open Properties (right-mouse click). In Java Build Path select Libraries and Add Library… Select IvyDE. The Main settings are okay by default. On the Settings tab, select ivysettings.xml from the project.
