### ISSUE TITLE
Documentation for COMMAND_PATTERN variable

### ISSUE THREAD

**Issue by htmsousa** [unclebob/fitnesse#860]
Hello,

I was having an issue with my tests (java.lang.OutOfMemoryError: PermGen space) that were running on the VM started for SlimService. The solution to fix my problem is very simple as I just needed to increase the PermSize with -XX:MaxPermSize VM argument. After reading all Fitnesse documentation I couldn't find any way to set this VM configuration for SlimService.

Browsing the source code, I found that the VM is started in the ClientBuilder.java and that if the variable COMMAND_PATTERN is set then it will be used to start SlimService. After I set the variable as following, the PermGen issue was fixed.

`!define COMMAND_PATTERN {java -XX:MaxPermSize=128m cp %p %m}`

My only problem is that this "feature" is not documented anywhere and if the ClientBuilder changes the way it starts the VM, it may break this workaround.

Can you make this configuration "official" and document it in Fitnesse User Guide please?
Thank you.

**Comment by ggramlich** [comment]
I am not sure, whether you saw the descriptions on the following pages and are just missing the mention of MaxPermSize or you might just have missed these pages, because they are not well linked.
In any way: feel free to improve the documentation and send a pull request.

http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.CustomizingTestExecution
http://fitnesse.org/FitNesse.UserGuide.QuickReferenceGuide#GlobalVARIABLES

You might also consider providing the memory settings to the REMOTE_DEBUG_COMMAND, which is used in Debug mode instead of the COMMAND_PATTERN
http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.DebuggingFixtureCode

**Comment by htmsousa** [comment]
My mistake as I didn't find those pages. The existing documentation pages are good. 

As suggestion, a search mechanism across all documentation would be nice, or maybe the full documentation in one place (a web page or a PDF file) is enough.
