### ISSUE TITLE
Slim fixtures determine its own table type

### ISSUE THREAD

**Issue by LudovicVa** [unclebob/fitnesse#882]
I find myself defining fixtures that are intended to be used as a specific slim table.
So I have to tell my collaborators to use them with "query:/ddt:/etc..." or to add a call to the "define table type" fixture in their setup.

Why not use Java annotations on fixtures to set the default SlimTable (possibly overrided if specified in the test) to be used when calling this fixture ?
Another possibility would be to add a public method to the SlimTableFactory to define table type that would be called in the plugin for instance (the plugin would then be the fixture project itself, which makes sense in my use case but I'm not sure it is the way to go).

If you are OK with this principle, I can do the modifications myself and then do a pull request.

**Comment by amolenaar** [comment]
Unfortunately, the handling of the fixture is done mostly on the wiki server side (that's why we need a table type there), so adding annotations does not really help here. The slim protocol itself is just a simple remote method invocation protocol, with no logic regarding the tables that are used. Hence, all logic about the tables is in the wiki server / test pages.

This might be something to take into account when upgrading the Slim protocol at some point.

I'm not sure what you mean by `add a public method to the SlimTableFactory`. You can add custom table types to Slim, so you could experiment.

**Comment by LudovicVa** [comment]
Indeed, the frontier between slim and fit wasn't clear enough in my head. Nevermind.
Would be nice to add a "get table type" in the protocol then.

For the "add a public method to the SlimTableFactory", I simply mean to add a method "addDefaultTableForFixture" (or something like this) that would add an element in the "tableTypeArrays" with the given parameters. It makes sense in the plugin that I am building as it is a plugin that creates "proxy" for underlying fixtures (for instance to give default parameters to the fixtures, or renames some field. I don't know if it is clear)

**Comment by six42** [comment]
Hi @LudovicVa,

did you looked at "define alias". This does what you want.

Would be good if you extend it to support defaults as well.

http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.DefineAlias

**Comment by amolenaar** [comment]
This was fixed by #884, right?

**Comment by LudovicVa** [comment]
Indeed it was closed by #884. However, I suggest keeping the idea to allow to determine the table type using the Slim protocol.
