### ISSUE TITLE
Exception handling with stack traces

### ISSUE THREAD

**Issue by yavski** [unclebob/fitnesse#899]
In addition to [Default handling of exceptions](http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ExceptionHandling), add support for stack traces at Slim protocol level. When used, the html page of the fixture can render both the message of the exception + a link to the stack trace when the message is clicked.

**Comment by amolenaar** [comment]
Hi, Can you elaborate on your proposal? What's the use case?

**Comment by fhoeben** [comment]
You can achieve something like this yourself, at the fixture level. You can have your fixture implement `InteractionAwareFixture` and in the method `aroundSlimInvoke()` catch any exception and instead of just throwing it throw an Exception like described in 'default handling of exceptions' where the message string put some HTML that controls what is shown in the wiki on exception.

I use this in my `BrowserTest` fixture to capture a screenshot (and embed that in the wiki page) and the full HTML of the page (and add a link to that in the wiki) on exception from Selenium, or when unable to locate an element on the page. See source in [hsac-fitnesse-fixtures](https://github.com/fhoeben/hsac-fitnesse-fixtures) for more details.

**Comment by amolenaar** [comment]
Can I close this issue?
