### ISSUE TITLE
Define table type does not work with "script table"

### ISSUE THREAD

**Issue by LudovicVa** [unclebob/fitnesse#943]
Hello,
Using the last version of Fitnesse, I noticed strange behavior when using "define table type" with scripts. It works fine with ddt and table, but it simply does not work when we use "script". It seems that the table is called as a decision table.
However, while debugging, it seems like the SlimTableFactory created the correct object (ScriptTable).

**Comment by amolenaar** [comment]
Do you have an example that exposes this issue. Something I can test with?

**Comment by LudovicVa** [comment]
Hello !

I simply add this to the DefineTableTypeTest:
`|Define Table Type |
| Table or Decision Fixture | as Script |

|Table Or Decision Fixture |
|check | parsingAs | Parsed as Decision fixture |

|script:Table Or Decision Fixture |
|check | parsingAs | Parsed as Decision fixture |`

The first call does not work, I get an exception on 2nd row : "The instance scriptTableActor.parsingAs. does not exist"
The second one works just fine !

**Comment by amolenaar** [comment]
It goes wrong on ScriptTable.java:111, since our first cell does not contain our keyword "script".

This code has been put in place to make script and scenario table cooperate with each other. E.g. you could have subclassed a script table or instantiate a scenario table as a script.

Fixing this properly is not easy (down the rabbit hole we go...)

**Comment by amolenaar** [comment]
Merged
