### ISSUE TITLE
How to trigger email after fitnesse slim test run?

### ISSUE THREAD

**Issue by ChethanGB** [unclebob/fitnesse#957]
Hi Fitnesse Group,

We are using Fitnesse slim in our project. As of now we are,

    Running the Fitnesse server manually.
    Executing the fitnesse test/suite (slim) from wiki page manually and
    We are checking the results manually from wiki itself.

Now, we are planning to implement Continuous Delivery for our project. We are using Anthilpro as an integration tool.

Note: We are planning to use Jenkins in the later stage.

So, is there a way to,

    Integrate Fitnesse slim with AnthilPro / Jenkins (CI tools).
    Run Fitnesse server from CI Server.
    Rum Tests / Suits from CI Server.
    Convert the generated results into mailable format and send the execution results to specified set of email IDs ?

Kindly help me out.

Note: I know there is a fitnesse plugin for Jenkins to take care of this. But, it is not working for me.

**Comment by amolenaar** [comment]
Hi,

Although this is a message better posted at the mailing list, I'll provide my answer/view on running FitNesse.

You can easily run FitNesse from a build tool like Maven or Gradle. The build tool gives you the confidence that what you run locally will also run on a build server. Set up a couple of tasks, e.g. for running the desired suites and one for starting the server in interactive mode.

Personally I prefer Gradle, since it provides you more options to create custom tasks than Maven, but I've had succes with both tools.

With regards to the mailable format: that kind of depends on the capabilities of the build server. You can output text (e.g. call a suite with the option `format=text`) for a start.

Here are some example setups:
- Maven: https://github.com/xebia/Xebium (`pom.xml`)
- Gradle: https://github.com/fitnesse/fitnesse-git-plugin (`build.gradle`)

**Comment by amolenaar** [comment]
Close issue as discussion continues on the mailing list.
