### ISSUE TITLE
Markup Literal Text displays unexpected behavior when using <>

### ISSUE THREAD

**Issue by keetron** [unclebob/fitnesse#988]
There is a text with a link that goes something like this:
`<<something something>>`

I want to click that and so the logical thing to do is to code it like this:
`!-<<something something>>-!`
This is however displayed in the wiki as
`<>`
The test will run and succeed tho, unless ran as part of a suite when it will fail.

So I use
`!<<<something something>>>!`
This is displayed as `!<<<something something>>>!`
This fails immediately, it cantno find the link to click. In the report it is displayed as `<<>>`

The I tried the text just as text in the code:
`<<something something>>`
This is then displayed in the wiki as:
`<<something something>>`
The test succeeds ran single but fails as a suite, again the report says it is `<>` that cannot be found.

Normally my solution would be to either go to the link not by clicking the text but by label id or tell the developers to remove the stupid `<<>>` surrounding the text but today is not such a day. I will try tomorrow but at the same time I thought you wanted to know the strange behavior of the wiki when it comes to `<<>> `especially when running a suite.

**Comment by keetron** [comment]
And for some reason the above markup is foo'd as well.

**Comment by jediwhale** [comment]
When you use literal markup !-<<something something>>-! you are saying you want the HTML to contain the string <<something something>>. Your browser tries to interpret this but <something something> is an illegal HTML tag so the browser just ignores it and displays <>.  When you just use the string <<something something>>, Fitnesse converts this to &lt;&lt;something something&gt;&gt; so it appears as expected in your browser.  When Fitnesse passes this string to your fixture, it converts it back to its original form so your test passes.

So the markup is all behaving as expected, and you say your test passes when run alone.  Since your test fails when run in a suite, I expect this has nothing to do with the markup but is caused by some interaction between your test and a previous test.  For us to help with that, we need more information about what your test suite does.

**Comment by keetron** [comment]
I should have updated this.
In the end the fails in the suite were due to a previous testcase not cleaning up the cookies, which obviously is no issue when ran alone. Because this testcase is so dependent on the absence of cookies, I have it clean up before anything else. Seeing no other test in this project cleans up cookies it seems more logical to add the cleanup line to the test having an issue with cookies present.
Finally I asked the team not to use these horrible labels anymore but what do I know :-)
