### ISSUE TITLE
When using the Euro-symbol in a decision table, FitNesse errors out "cannot connect to SUT"

### ISSUE THREAD

**Issue by keetron** [unclebob/fitnesse#995]
The title says it all, when running a test with the Euro-symbol €, the test fails to connect to the SUT. Removing the symbol resolves this, but the test then fails of course. Is this known behavior? I tried putting !- -! around the expression but it made little difference.

Console gives this error:
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]

**Comment by six42** [comment]
Hi Keetron,

€ works nicely for me.

can you try if below test works as it is first and second after you add a €:
http://localhost:8001/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.MultiByteCharsInSlim

Which version of FitNesse, which OS and which programming language are you using? 

![euro](https://cloud.githubusercontent.com/assets/5906592/20815525/802f779c-b81e-11e6-8718-1f1af6aee445.JPG)

**Comment by keetron** [comment]
We are actually using quite the Christmas tree of addons to do what we want to do.

First, we use the latest fitnesse on Windows 7 with the HSAC plugin.
Second, the value from the decision table with the € is used in a table template that puts it in a map so we can use it to modify XML stubs as well as use/check the value in the screen and later to validate the output XMLs as well.
Finally this all runs in a VM.

I blaim hsac to be honest, right now I moved the testcase to the comment table "framework has issues with €" and I'll focus on the dynamic stubbing more as that has much wider use and impact to get working right.

**Comment by fhoeben** [comment]
On Windows 7, IBM JVM 7 64bit http://localhost:8001/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.MultiByteCharsInSlim causes the same problem as mentioned by @keetron.
Adding `!define slim.port {0}` to .FitNesse.SuiteAcceptanceTests.SuiteSlimTests fixes the problem and makes the test green.

**Comment by keetron** [comment]
Yes, that fixed it. Checked when running the test individually or in a suite.

**Comment by amolenaar** [comment]
I tried with the Win7+IE10 box from http://modern.ie, and can not reproduce the error.

<img width="206" alt="screen shot 2017-01-14 at 21 53 32" src="https://cloud.githubusercontent.com/assets/96249/21958002/eaf85a1a-daa3-11e6-89c4-1d52e12d7236.png">

I also tried with a different code page (1142, Nordic), but all seemed to work okay.

What could be the cause of those errors?

**Comment by fhoeben** [comment]
I don't know what could cause this. Which version of win7 did you use. 64 or 32 bit, which version of Java (32 or 64 bit, which vendor)?
We had this problem on 64 bit Win7, with 64 bit IBM JDK.

**Comment by fhoeben** [comment]
I restested with other JVMs (Oracle 1.7 and 1.8 32-bit, Oracle 1.8 64bit). I was only able to reproduce the problem using the IBM JDK 1.7 64 bit.
So it probably is (yet another) annoying problem inside that JVM. So using another JVM is another workaround (besides forcing a port to be used instead of stdin/-out)

On the other hand: it still isn't clear to me what the advantage is of communicating over stdin and -out over just using a free port?

Maybe it would also be good to log problems where the Slim process breaks the connection to the wiki process to a file on disk. This problem (I believe) is caused by a problem in the Slim process where an exception is thrown, causing the process to be terminated but since no data can be sent to the wiki process the stack trace cannot be sent to the wiki making it unavailable to aid debugging. A file on disk would be helpful in such an event...

**Comment by amolenaar** [comment]
Thanks for the testing. I used Win7, 32 bit with Oracle Java 8 (patch 112). 

There are some advantages over using a pipe rather than a TCP connection. First of all you do not need a TCP connection, which is particularly handy if you run on something like a CI machine. We spawn a process and immediately have a handle for communication. 

To send out some extra information when the process is about to crash we can also add an exit-handler. Although I would assume that an exit handler could do the trick as well (in case somebody calls a `System.exit(1)` for example). I have to admit there are some caveats in the way the communication is structured now.
